# Generated by Django 4.2.5 on 2023-09-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(default=0, editable=False, help_text='Book Unique Key', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Book Title', max_length=100)),
                ('writer', models.CharField(help_text='Book Writer', max_length=100)),
                ('publisher', models.CharField(help_text='Book Publisher', max_length=100)),
                ('publication_date', models.DateField(help_text='Bool Publication Date')),
            ],
            options={
                'verbose_name': '도서 정보',
                'verbose_name_plural': '도서 정보',
                'ordering': [],
            },
        ),
    ]
