# Generated by Django 4.2.5 on 2023-09-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_book_id_alter_book_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
