# Generated by Django 4.2.5 on 2023-09-17 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0002_alter_search_options_remove_search_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='search_datetime',
        ),
    ]
