# Generated by Django 4.2.5 on 2023-09-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0003_remove_search_search_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search_id',
            field=models.IntegerField(help_text='Sentence Search Key', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='search',
            name='sentence',
            field=models.TextField(help_text='Search Sentence'),
        ),
    ]
