# Generated by Django 4.2.5 on 2023-09-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_remove_book_writer_book_author_and_more'),
        ('searches', '0006_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='book_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='search_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='search',
            name='sentence',
            field=models.TextField(default='', null=True),
        ),
    ]
