# Generated by Django 4.2.5 on 2023-09-19 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_remove_book_writer_book_author_and_more'),
        ('searches', '0007_answer_book_id_alter_answer_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='book_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
