# Generated by Django 4.2.5 on 2023-09-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0008_alter_answer_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='book_id',
        ),
    ]
